name: "Report a documentation issue"
description: Report an issue with the Next.js documentation.
title: "Docs: "
labels:
  - "Documentation"
body:
  - type: markdown
    attributes:
      value: |
        Hello world
  - type: markdown
    attributes:
      value: Thank you for helping us update our docs!
  - type: textarea
    attributes:
      label: What is the documentation issue?
      description: "Example: There is incorrect or stale information about the `<Link>` component."
    validations:
      required: true
  - type: textarea
    attributes:
      label: Is there any context that might help us understand?
      description: A clear description of any added context that might help us understand.
    validations:
      required: true
  - type: input
    attributes:
      label: Does the docs page already exist? Please link to it.
      description: "Example: https://nextjs.org/docs/app/api-reference/components/link"
    validations:
      required: false
